# Dockerfile to install UKAT
FROM python:3.7

# Install Dependencies
RUN apt-get update && apt-get upgrade -y && \
	apt-get install -y build-essential pkg-config cmake git pigz && \
	apt-get clean -y && apt-get autoclean -y && apt-get autoremove -y

# Get dcm2niix from github and compile
RUN cd /tmp && \
	git clone https://github.com/rordenlab/dcm2niix.git && \
	cd dcm2niix && mkdir build && cd build && \
	cmake -DBATCH_VERSION=ON -DUSE_OPENJPEG=ON .. && \
	make && make install

RUN pip install pydicom pandas openpyxl
RUN pip install git+https://github.com/spmic-uon/xnatc

ADD version.txt .
ADD dicom_qc.py .
ADD ukrin_conf.xlsx .


