# Dockerfile to install UKAT
FROM python:3.7

# Install Dependencies
RUN apt-get update && apt-get upgrade -y && \
	apt-get install -y build-essential pkg-config cmake git pigz && \
	apt-get clean -y && apt-get autoclean -y && apt-get autoremove -y

# Changing value of this argument will force reinstallation of all python packages
ARG REINSTALL_FORCE=pudding3
RUN pip install pydicom pandas openpyxl xnat_nott requests

ADD version.txt .
ADD dicom_qc.py .
ADD ukrin_conf.xlsx .
